{%set name = "textract" %}
{%set version = "1.6.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "86b31dccdde8a31a0f5f307ae384590ba1f7ebd09640acd15f1b178a0b02" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - argcomplete
    - chardet
    - python-pptx >=0.5.1
    - pdfminer.six
    - docx2txt
    - beautifulsoup4
    - xlrd
    - ebooklib
    - speechrecognition >=3.1.0
    - msg-extractor
    - six

test:
  imports:
    - textract
    - textract.cli
    - textract.colors
    - textract.exceptions
    - textract.parsers
    - textract.parsers.audio
    - textract.parsers.csv_parser
    - textract.parsers.doc_parser
    - textract.parsers.docx_parser
    - textract.parsers.eml_parser
    - textract.parsers.epub_parser
    - textract.parsers.gif_parser
    - textract.parsers.html_parser
    - textract.parsers.image
    - textract.parsers.jpg_parser
    - textract.parsers.json_parser
    - textract.parsers.mp3_parser
    - textract.parsers.msg_parser
    - textract.parsers.odt_parser
    - textract.parsers.ogg_parser
    - textract.parsers.pdf_parser
    - textract.parsers.png_parser
    - textract.parsers.pptx_parser
    - textract.parsers.ps_parser
    - textract.parsers.rtf_parser
    - textract.parsers.tiff_parser
    - textract.parsers.txt_parser
    - textract.parsers.utils
    - textract.parsers.wav_parser
    - textract.parsers.xls_parser
    - textract.parsers.xlsx_parser

  commands:
    - textract -h

about:
  home: https://github.com/deanmalmgren/textract
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extract text from any document. no muss. no fuss.
  doc_url: https://textract.readthedocs.io/en/latest/
  dev_url: https://github.com/deanmalmgren/textract

extra:
  recipe-maintainers:
    - pmlandwehr
    - CurtLH
