{% set name = "textract" %}
{% set version = "1.6.3" %}
{% set sha256 = "6213b2f923b85af8e5e380241db9361e3f5dbd444a74108745fd4121ae151310" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - argcomplete
    - chardet
    - python-pptx >=0.5.1
    - pdfminer.six
    - docx2txt
    - beautifulsoup4
    - xlrd
    - ebooklib
    - speechrecognition >=3.1.0
    - msg-extractor
    - six

test:
  imports:
    - textract
    - textract.cli
    - textract.colors
    - textract.exceptions
    - textract.parsers
    - textract.parsers.audio
    - textract.parsers.csv_parser
    - textract.parsers.doc_parser
    - textract.parsers.docx_parser
    - textract.parsers.eml_parser
    - textract.parsers.epub_parser
    - textract.parsers.gif_parser
    - textract.parsers.html_parser
    - textract.parsers.image
    - textract.parsers.jpg_parser
    - textract.parsers.json_parser
    - textract.parsers.mp3_parser
    - textract.parsers.msg_parser
    - textract.parsers.odt_parser
    - textract.parsers.ogg_parser
    - textract.parsers.pdf_parser
    - textract.parsers.png_parser
    - textract.parsers.pptx_parser
    - textract.parsers.ps_parser
    - textract.parsers.rtf_parser
    - textract.parsers.tiff_parser
    - textract.parsers.txt_parser
    - textract.parsers.utils
    - textract.parsers.wav_parser
    - textract.parsers.xls_parser
    - textract.parsers.xlsx_parser

  commands:
    - textract -h
    - pip check
    
  requires:
    - pip

about:
  home: https://github.com/deanmalmgren/textract
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extract text from any document. no muss. no fuss.
  doc_url: https://textract.readthedocs.io/en/latest/
  dev_url: https://github.com/deanmalmgren/textract

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
